plottool: write bytes to port instead of unicode strings
python-serial complains:

  File "plottool.py", line 133, in <module>
    port.write("PU0,0;SP0;SP0;")
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 532, in write
    d = to_bytes(data)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 63, in to_bytes
    raise TypeError('unicode strings are not supported, please encode to bytes: {!r}'.format(seq))
  TypeError: unicode strings are not supported, please encode to bytes: 'PU0,0;SP0;SP0;'